# Generated by Django 4.2.9 on 2024-01-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_name", models.CharField(max_length=255)),
                ("brand", models.CharField(max_length=255)),
                ("fuel_type", models.CharField(max_length=50)),
                ("mileage", models.IntegerField()),
            ],
        ),
    ]
