# Generated by Django 4.2.9 on 2024-01-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
