# Generated by Django 4.2.9 on 2024-01-20 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0002_car_year"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="year",
        ),
    ]
